CREATE TABLE DATATYPE(
Name VARCHAR(50) NOT NULL,
PRIMARY KEY(Name)
);
CREATE TABLE LOCATION(
City VARCHAR(50) NOT NULL,
State VARCHAR(50) NOT NULL,
PRIMARY KEY(City,State)
);
CREATE TABLE POI(
Name VARCHAR(100) NOT NULL,
Zipcode VARCHAR(10) NOT NULL,
Date_Time_Flagged TIMESTAMP,
Flagged BOOLEAN NOT NULL,
City VARCHAR(50) NOT NULL,
State VARCHAR(50) NOT NULL,
PRIMARY KEY(Name),
FOREIGN KEY(City, State) REFERENCES LOCATION(City,State) ON DELETE
CASCADE ON UPDATE CASCADE
);
CREATE TABLE DATAPOINT(
DpDate DATE NOT NULL,
DpTime TIME NOT NULL,
Value INT NOT NULL,
Pending INT,
DataType VARCHAR(50) NOT NULL,
POI VARCHAR(100) NOT NULL,
PRIMARY KEY(DpDate, DpTime),
FOREIGN KEY(POI) REFERENCES POI(Name) ON DELETE CASCADE ON UPDATE
CASCADE,
FOREIGN KEY(DataType) REFERENCES DATATYPE(Name) ON DELETE CASCADE
ON UPDATE CASCADE
);
CREATE TABLE USER(
Username VARCHAR(30) NOT NULL,
Email VARCHAR(50) NOT NULL,
Password VARCHAR(30) NOT NULL,
Usertype VARCHAR(30) NOT NULL,
PRIMARY KEY(Username),
UNIQUE(Email)
);
CREATE TABLE CITYOFFICIAL(
Username VARCHAR(30) NOT NULL,
Title VARCHAR(30) NOT NULL,
City VARCHAR(50) NOT NULL,
State VARCHAR(50) NOT NULL,
Pending INT,
PRIMARY KEY(Username),
FOREIGN KEY(Username) REFERENCES USER(Username) ON DELETE CASCADE
ON UPDATE CASCADE ,
FOREIGN KEY(City, State) REFERENCES LOCATION(City, State) ON DELETE
CASCADE ON UPDATE CASCADE
);
